### ISSUE TITLE
Having no 1-wire devices (DS18B20) results in an unrecoverable error

### ISSUE THREAD

**Issue by cogfor** [Thomas-GeDaD/SignalK_raspberry_MCS#2]
Situation:
Using a fresh Raspberry OS arm64 install and the Gedad Marine Control Server attached to the Raspberry with no devices

Observed behavior:
When trying to enable the MCS Signal K plugin an error appears:

`.properties['configuration'].properties['devices'].items.properties['oneWireId'].enum should be array
.properties['configuration'].properties['devices'].items should be array
.properties['configuration'].properties['devices'].items should match some schema in anyOf`

Also see the attached screenshot.

<img width="1152" alt="Screenshot 2020-10-01 at 13 43 01" src="https://user-images.githubusercontent.com/1834325/94810464-53564b80-03f4-11eb-8669-bdd68751444e.png">

**Comment by Thomas-GeDaD** [comment]
You only need to activate the plugin when you have connected a 1-wire sensor. The Plugin only shows you information.
The rest does the postinstall script.
I worked on the update and change this behavor on the next version when I intigrate the input read.

**Comment by Thomas-GeDaD** [comment]
https://github.com/Thomas-GeDaD/SignalK_raspberry_MCS/blob/3c79db19525f0e8f44ad444424586bf067111215/index.js#L20
Have fix this in the next version...

**Comment by Thomas-GeDaD** [comment]
the new update 1.0.4 is published and there is fixed this error....
