### ISSUE TITLE
Installing the plugin only works on Raspberry OS (Ubuntu for Raspberry fails) 

### ISSUE THREAD

**Issue by cogfor** [Thomas-GeDaD/SignalK_raspberry_MCS#3]
The plugin uses absolute filepaths that are specific for Raspberry OS. This prevents installing the plugin on alternative Linux operating systems for Raspberry Pi.

Examples for Ubuntu:
* `/boot/config.txt` for dtoverlays. This is `/boot/firmware/usercfg.txt` on Ubuntu
*  `/etc/network/interfaces.d/`. Ubuntu uses `netplan` which has a different configuration

I also had issues installing pigpio (`apt-get install python3 idle3 pigpio python-pigpio python3-pigpio -y` not working).

**Comment by Thomas-GeDaD** [comment]
This Plugin is ONLY for Raspberry OS (Buster)! Not for Ubuntu. I implement an control algorythm for checking this before so that you cannot install in a wrong environment! Many hardware based things did not work like this.

**Comment by cogfor** [comment]
I tried to install the plugin on Ubuntu on my Pi. It worked, but the `postinstall.js` script failed due to various path problems.Is that what you mean by your control algorithm?

Now that Ubuntu is out for Raspberry I think the documentation and plugin should clearly state it only works on Raspberry OS. Especially since the plugin is installed through the Signal web interface where users don't have the full installation manual available.

Consider this as something for the future. Thanks for the great MCS board!

**Comment by Thomas-GeDaD** [comment]
I intigrate this in the readme...;-)
At the moment i have no Ubuntu skills, when i have the plugin ready i try to intigrate this also in other OS for the pi...

**Comment by Thomas-GeDaD** [comment]
First of all I have describe it in the readme:
https://github.com/Thomas-GeDaD/SignalK_raspberry_MCS/commit/7583c12513a5039c2894ae81944222e25cdfc2fb
I think the only challenge ist to get the postinstall wor on ubuntu. So the script must scheck which os and adjust the pathes...
