### ISSUE TITLE
Allow for configurable calibration offsets

### ISSUE THREAD

**Issue by thepeb12** [Thomas-GeDaD/SignalK_raspberry_MCS#5]
It would be nice to be able to configure a calibration offset for e.g. temperature sensors? For example + 0,5 degrees or - 0,3. For both I2C and 1-wire sensors.

**Comment by Thomas-GeDaD** [comment]
Thats a good idear.. 
I implement it for 1-wire (DS18b20) that are directly supported in the Plugin.
For i2c i cannot do this, because you need a other Plugin in SignalK for the type of Sensor you use.
So if you want to have this future for the kind of Sensor you use, make a request in the Plugin you use. ;-)

**Comment by Thomas-GeDaD** [comment]
https://github.com/Thomas-GeDaD/SignalK_raspberry_MCS/commit/f85effdcb603a1372522ea3ec7541ffe1254052f

**Comment by Thomas-GeDaD** [comment]
Have add it. Comes with the next update soon...

**Comment by Thomas-GeDaD** [comment]
The new update is available. After update, you can set an offset....

**Comment by thepeb12** [comment]
Excellent job! Will test it out immediately.

**Comment by Thomas-GeDaD** [comment]
did all work for you?

**Comment by thepeb12** [comment]
Hi, yes it did. Initially the offset field was empty and then I simply got a NULL value reported but the second I entered anything I started to get data. 
I couldn't see any explanation in the doc file. Would be nice to know how the offset works. Does it support - numbers?

**Comment by Thomas-GeDaD** [comment]
Yes, numbers like 1, -1, -1,73254, 0,23 etc

**Comment by Thomas-GeDaD** [comment]
I add it to the docs..

**Comment by Thomas-GeDaD** [comment]
a4769f2c5a66646f224c8c2877e6d876594a903f

**Comment by thepeb12** [comment]
Excellent.. Many thanks
