### ISSUE TITLE
Restarting the Raspberry PI requires an additional restart of SignalK

### ISSUE THREAD

**Issue by qMalte** [Thomas-GeDaD/SignalK_raspberry_MCS#7]
Hello, when I restart the Raspberry PI, I do not get any data in SignalK from my temperature sensors which are connected via OneWire. Only when I separately restart SignalK again, the data is displayed again. Is such a problem already known?

**Comment by Thomas-GeDaD** [comment]
Hi, sorry for the delay.
I tried to reproduce the error, but i didn´t get it.
This only can happen, when Signalk starts before the service has started. Do you have some further changes on your system? Which kernel do you use?
Thomas

**Comment by Thomas-GeDaD** [comment]
UPdates? Else I close...

**Comment by qMalte** [comment]
Hi Thomas,

please excuse the late feedback.

I have now tested it again with different Raspberry PI operating system versions and the error still occurred.

Operating systems used:
Raspberry PI OS (Desktop) 32 and 64 Bit
Openplotter v3 Image 32 and 64 Bit

Currently I have solved it so that the PI runs a script through a cronjob, which restarts the SignalK server using systemctl. Of course this is not the nicest solution.

I did not make any changes to the systemctl settings on the operating system itself.

Can you tell me which service on the PI is responsible for the functionality of the 1-Wire sensors. Then I would try to modify the start of SignalK at boot so that this service has to be started first before SignalK is started.

I am looking forward to your feedback.


Many greetings
Malte

**Comment by qMalte** [comment]
Update: I have now added a timeout to the systemd startup file of the SignalK service:

`ExecStartPre=/bin/sleep 30`

to

`/etc/systemd/system/signalk.service`

This also works without any problems, but of course not optimally. It would certainly be best to start the service deliberately after another one.

**Comment by Thomas-GeDaD** [comment]
I will change the code to check for new sensors in an interval. Then this issue should be solve. Further it should be possible to add new sensors to a running system.
Hope i have some time for this the next days.
Thomas

**Comment by Thomas-GeDaD** [comment]
https://github.com/Thomas-GeDaD/SignalK_raspberry_MCS/commit/5abf3a864a0f2c61ff31d083c0b15ec1cb5c6270
I will check the code the next days. First i have to setup a system for testing.

**Comment by Thomas-GeDaD** [comment]
solved
