### ISSUE TITLE
Is spi-bcm2835-overlay needed on bullseye?

### ISSUE THREAD

**Issue by mgrouch** [Thomas-GeDaD/SignalK_raspberry_MCS#9]
I think it’s not needed and breaking other things.

**Comment by Thomas-GeDaD** [comment]
Id seems to be not needed any more. I will check this and delete it from postinstall.

**Comment by Thomas-GeDaD** [comment]
https://github.com/Thomas-GeDaD/SignalK_raspberry_MCS/commit/9c5d5b01d5f98ca7c55b8a1edf115035c4500167
